version: "2"
services:
  app: &app
    build: .
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_SSL_HOST: mysql-ssl
      MYSQL_DB_SSL_BAD_CN_HOST: mysql-different-cn
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
    links:
      - mysql
  # for development purposes
  dev:
    <<: *app
    volumes:
        - ./:/code
        - ./data:/data
    environment:
      - KBC_DATADIR=./data
      - KBC_CONFIGID=12345
      - KBC_COMPONENTID=kds-team.ex-mysql-next
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: mysqld --local-infile --port=3306 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword
  test:
    # Use to run flake8 and unittests checks
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_DATADIR=./data
    command:
      - /bin/sh
      - /code/scripts/build_and_test.sh

